language: python
python:
    - "2.7"

env:
    - PLATFORMIO_CI_SRC=examples/SimpleIR

install:
    - python -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"

script:
    - platformio ci --lib="." --board=uno --board=pro16MHzatmega168